- name: What's New
  description: Discover the latest product additions to the Singapore Government Developer Portal here
  items:
    - Overview
    - CloudScape
    - 'I2C {{Infra to Code}}'
    - MyMoneySense
    - Notarise
    - Secure Infrastructure-as-Code
    - TechBiz
    - Transcribe

- name: Citizen-facing Products
  description: Explore the government products for providing citizens with the services they need. This includes citizen life journey, grant services, and more!
  items:
    - Overview
    - BookingSG
    - COVID-19 Chatbots
    - eCanvas
    - ePad
    - GovWallet
    - Government Assisted Living Ecosystem
    - GoWhere Suite
    - HealthCerts
    - Identiface
    - LifeSG
    - Login
    - MyInfo
    - Notarise
    - OurSG
    - Personal Alert Button
    - SafeEntry
    - SGFinDex
    - Singpass
    - SmartGym
    - Space Out
    - TraceTogether
    - Verify

- name: Data Science and Artificial Intelligence
  description: Access Data Science and Artificial Intelligence (DSAI) products developed by the Singapore Government, best practices and other resources here.
  items:
    - Overview
    - VAS
    - Analytics by Design
    - Data Literacy ePrimer

- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - Asynchronous Data Exchange
    - APEX
    - Cloud File Transfer
    - Container Stack
    - Corppass
    - DECADA IoT Tech Stack
    - Identiface
    - Login
    - Myinfo
    - Personalise
    - SHIP-HATS
    - Singapore Government Design System
    - Secure Infrastructure-as-Code
    - StackOps
    - TechBiz
    - Transcribe
    - VAS
    - Verify
    - WOGAA
