<template>
  <div id="article-editor-app">
    <a class="sgds-button is-rounded is-small" @click="showEditorModal = true"
      >Edit This Page</a
    >
    <Modal v-if="showEditorModal">
      <template v-slot:header>
        <button
          class="sgds-button is-rounded"
          type="button"
          @click="showEditorModal = false"
        >
          <span class="sgds-icon sgds-icon-cross"></span>
        </button>
      </template>
      <ArticleEditor
        editorType="edit"
        :page_title="title"
        :page_layout="layout"
        :page_category="category"
        :page_description="description"
        :page_path="url"
        :page_content="content"
        :page_collection="collection"
        :page_categories="
          categories
            ? JSON.parse(this.categories).filter(category => category)
            : null
        "
        @close="showEditorModal = false"
      />
    </Modal>
  </div>
</template>

<script>
import ArticleEditor from "../lib/ArticleEditor.vue";
import Modal from "../lib/Modal.vue";

export default {
  props: {
    title: {
      // From front matter
      type: String,
      requred: true
    },
    layout: {
      // From front matter
      type: String,
      required: true
    },
    category: {
      // From front matter
      type: String,
      required: true
    },
    description: {
      // From front matter
      type: String
    },
    url: {
      // Generated by Jekyll, should map to actual file path
      type: String,
      required: true
    },
    content: {
      // From Jekyll render. HTML.
      type: String,
      required: true
    },
    collection: {
      type: String,
      required: true
    },
    categories: {
      type: String // JSON array string
    }
  },
  components: { ArticleEditor, Modal },
  data() {
    return {
      page_content: null,
      showEditorModal: false
    };
  }
};
</script>
