<template>
    <div id="article-editor-app">
        <a class="sgds-button is-rounded is-small" @click="openEditor">Edit This Page</a>
    </div>
</template>

<script>
import ArticleEditor from "./ArticleEditor.vue";

export default {
    props: {
        title: {
            // From front matter
            type: String,
            requred: true
        },
        layout: {
            // From front matter
            type: String,
            required: true
        },
        category: {
            // From front matter
            type: String,
            required: true
        },
        description: {
            // From front matter
            type: String
        },
        url: {
            // Generated by Jekyll, should map to actual file path
            type: String,
            required: true
        },
        content: {
            // From Jekyll render. HTML.
            type: String,
            required: true
        },
        type: {
            type: String,
            required: true
        }
    },
    data() {
        return {
            page_content: null
        };
    },
    methods: {
        openEditor() {
            this.$modal.show(
                ArticleEditor,
                {
                    page_title: this.title,
                    page_layout: this.layout,
                    page_category: this.category,
                    page_description: this.description,
                    page_path: this.url,
                    page_content: this.content,
                    page_type: this.type
                },
                {
                    clickToClose: false,
                    width: "90%",
                    height: "auto",
                    minWidth: 250,
                    minHeight: 400,
                    scrollable: true
                }
            );
        }
    }
};
</script>